name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: {}

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    container: python:${{ matrix.python }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.14', python: '3.14', tox: py313}
          - {name: '3.13', python: '3.13', tox: py313}
          - {name: 'format', python: '3.14', tox: format}
          - {name: 'mypy', python: '3.14', tox: mypy}
          - {name: 'pep8', python: '3.14', tox: pep8}
          - {name: 'package', python: '3.14', tox: package}

    steps:
      - uses: pgjones/actions/tox@64fb3fd1840712671bd6f792e5b803f53f63fbdf # v1.1
        with:
          environment: ${{ matrix.tox }}

  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest

    steps:
      - uses: pgjones/actions/zizmor@64fb3fd1840712671bd6f792e5b803f53f63fbdf # v1.1
